### ISSUE TITLE
socket.error: [Errno 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by jvidin** [safesoftware/fme-standalone-engine#1]
Trying to get going with docker and fme , bumping into the folowing 
I started the docker services with start_containers.ps1 i can see both services when running docker service ls

```
PS C:\PythonProjects\github-fme-standalone-engine> docker service ls
ID            NAME        MODE        REPLICAS  IMAGE
fnfd69gg6yeh  web         replicated  0/1       httpd:alpine
h1r2uxrbjxkc  fme_engine  replicated  0/1       safesoftware/fme-engine-2017:latest
```

ERROR Below 
```
C:\Python27.13\python.exe C:/PythonProjects/github-fme-standalone-engine/FMEEngineClient.py localhost 7777 "AirQualityReport.fmw --Location Vancouver"
Traceback (most recent call last):
  File "C:/PythonProjects/github-fme-standalone-engine/FMEEngineClient.py", line 21, in <module>
    s.connect((TCP_IP, int(TCP_PORT)))
  File "C:\Python27.13\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10061] No connection could be made because the target machine actively refused it

Process finished with exit code 1
```

Any tips how to trouble shoot this ?

Thanks in advance

**Comment by garnold54** [comment]
In the `docker service ls` you posted, both `REPLICAS` are `0/1` which means the containers are not running. In the directory that you checked this repository out to, try creating two folders, one called `logs` and one called `results`, and I think it should all come up.

I believe it is failing because docker is trying to mount these directories into the containers and they don't exist so it is failing.

**Comment by jvidin** [comment]
Fight continues ... 
Mounts finaly done , replicas created , volumes mapped 

```
PS C:\docker_area\fme-standalone-engine> docker service ls
ID            NAME        MODE        REPLICAS  IMAGE
6av56n3g0di4  viz         replicated  1/1       dockersamples/visualizer:latest
kx9dudx5lggo  fme_engine  replicated  10/10     safesoftware/fme-engine-2017:latest
```

```
"Mounts": [
    {
        "Type": "bind",
        "Source": "/C/docker_area/fme-standalone-engine/workspaces",
        "Target": "/fmeengine/workspaces"
    },
    {
        "Type": "bind",
        "Source": "/C/docker_area/fme-standalone-engine/results",
        "Target": "/fmeengine/results"
    },
    {
        "Type": "bind",
        "Source": "/C/docker_area/fme-standalone-engine/logs",
        "Target": "/fmeengine/logs"
    }
],
```
But now failing at:
```
C:\Python273.64\python.exe C:/docker_area/fme-standalone-engine/FMEEngineClient.py localhost 7777 "AirQualityReport.fmw --Location Vancouver"
261002:File AirQualityReport.fmw could not be opened|LogFileName=job_.log

Process finished with exit code 0
```
Thanks and have fun at UC .

**Comment by jvidin** [comment]
Ok got it to work now. On Docker for windows we need to be sure that we share local drives so they are available to containers.   
![image](https://cloud.githubusercontent.com/assets/1880658/26444509/a4854064-4134-11e7-9841-36b65f9eee3e.png)
